export const CREATE_APPOINTMENT = {
    REQUEST:"CREATE_APPOINTMENT_REQUEST",
    SUCCESS:"CREATE_APPOINTMENT_SUCCESS",
    FAIL:"CREATE_APPOINTMENT_FAIL",
}


export const GET_APPOINTMENTS = {
    REQUEST:"GET_APPOINTMENTS_REQUEST",
    SUCCESS:"GET_APPOINTMENTS_SUCCESS",
    FAIL:"GET_APPOINTMENTS_FAIL",
}
