export const CREATE_PATIENT = {
    REQUEST:"CREATE_PATIENT_REQUEST",
    SUCCESS:"CREATE_PATIENT_SUCCESS",
    FAIL:"CREATE_PATIENT_FAIL",
}

export const GET_PATIENT = {
    REQUEST:"GET_PATIENT_REQUEST",
    SUCCESS:"GET_PATIENT_SUCCESS",
    FAIL:"GET_PATIENT_FAIL",
}

export const GET_PATIENTS = {
    REQUEST:"GET_PATIENTS_REQUEST",
    SUCCESS:"GET_PATIENTS_SUCCESS",
    FAIL:"GET_PATIENTS_FAIL",
}

export const UPDATE_PATIENT = {
    REQUEST:"UPDATE_PATIENT_REQUEST",
    SUCCESS:"UPDATE_PATIENT_SUCCESS",
    FAIL:"UPDATE_PATIENT_FAIL",
}

export const DELETE_PATIENT = {
    REQUEST:"DELETE_PATIENT_REQUEST",
    SUCCESS:"DELETE_PATIENT_SUCCESS",
    FAIL:"DELETE_PATIENT_FAIL",
}

export const CREATE_CONTACT_TYPE = {
    REQUEST:"CREATE_CONTACT_TYPE_REQUEST",
    SUCCESS:"CREATE_CONTACT_TYPE_SUCCESS",
    FAIL:"CREATE_CONTACT_TYPE_FAIL",
}

export const GET_CONTACT_TYPE = {
    REQUEST:"GET_CONTACT_TYPE_REQUEST",
    SUCCESS:"GET_CONTACT_TYPE_SUCCESS",
    FAIL:"GET_CONTACT_TYPE_FAIL",
}

export const DELETE_CONTACT_TYPE = {
    REQUEST:"DELETE_CONTACT_TYPE_REQUEST",
    SUCCESS:"DELETE_CONTACT_TYPE_SUCCESS",
    FAIL:"DELETE_CONTACT_TYPE_FAIL",
}